package routers

import (
	"gin-web-template/internal/handler"
	"gin-web-template/internal/middlewares"
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "gin-web-template/docs" // docs is generated by Swag CLI
)

func CreateRouter() *gin.Engine {
	r := gin.Default()
	r.Use(middlewares.Cors())
	r.GET("/", func(c *gin.Context) { c.String(http.StatusOK, "hello") })

	// Swagger路由
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	apiGroup := r.Group("/api")

	// 不需要JWT验证的API路由组
	v1Group := apiGroup.Group("/v1")
	{
		v1Group.GET("/hello", handler.HelloHandler)
		v1Group.POST("/sessions", handler.LoginHandler)
		v1Group.POST("/user", handler.RegisterHandler)
		v1Group.POST("/user/password", handler.ChangePasswordHandler)
	}

	// 需要JWT验证的API路由组
	authGroup := apiGroup.Group("/v1")
	authGroup.Use(middlewares.JWTAuth())
	{
		authGroup.GET("/hello-user", handler.HelloUserHandler)
	}

	return r
}
